export const mockSubjectsData = [{
  id: 0,
  avatar: '/assets/images/trump.jpg',
  name: 'Donald Trump',
  biography: '45th President of the United States',
  date: 'Jan 1, 2018',
  isChecked: false,
  checkValue: 0,
  checkDate: 'Jan 1, 2018',
  isSelected: false,
  twitterHandle: '@donaldTrump.twitter',
  facebookHandle: '@donaldTrump.facebook',
  instagramHandle: '@donaldTrump.instagram'
}, {
  id: 1,
  avatar: '/assets/images/steve.jpg',
  name: 'Steve Jobs',
  biography: 'Co-founder of Apple Inc.',
  date: 'Feb 1, 2018',
  isChecked: false,
  checkValue: 0,
  checkDate: 'Jan 1, 2018',
  isSelected: false,
  twitterHandle: '@steveJobs.twitter',
  facebookHandle: '@steveJobs.facebook',
  instagramHandle: '@steveJobs.instagram'
}, {
  id: 2,
  avatar: '/assets/images/elon.jpg',
  name: 'Elon Musk',
  biography: 'Co-founder and CEO of Neuralink',
  date: 'Mar 1, 2018',
  isChecked: false,
  checkValue: 0,
  checkDate: 'Jan 1, 2018',
  isSelected: false,
  twitterHandle: '@elonMusk.twitter',
  facebookHandle: '@elonMusk.facebook',
  instagramHandle: '@elonMusk.instagram'
}, {
  id: 3,
  avatar: '/assets/images/jeff.jpg',
  name: 'Jeff Bezos',
  biography: 'Chief executive officer of Amazon',
  date: 'Jan 21, 2015',
  isChecked: false,
  checkValue: 0,
  checkDate: 'Jan 1, 2018',
  isSelected: false,
  twitterHandle: '@jeffBezos.twitter',
  facebookHandle: '@jeffBezos.facebook',
  instagramHandle: '@jeffBezos.instagram'
}, {
  id: 4,
  avatar: '/assets/images/warren.png',
  name: 'Warren Buffett',
  biography: 'Chairman and CEO of Berkshire Hathaway',
  date: 'Jan 1, 2018',
  isChecked: false,
  checkValue: 0,
  checkDate: 'Jan 1, 2018',
  isSelected: false,
  twitterHandle: '@warrenBuffet.twitter',
  facebookHandle: '@warrenBuffet.facebook',
  instagramHandle: '@warrenBuffet.instagram'
}, {
  id: 5,
  avatar: '/assets/images/face1.jpg',
  name: 'Smith Trump',
  biography: 'Web Developer',
  date: 'Jan 1, 2018',
  isChecked: false,
  checkValue: 0,
  checkDate: 'Jan 1, 2018',
  isSelected: false,
  twitterHandle: '@smithTrump.twitter',
  facebookHandle: '@smithTrump.facebook',
  instagramHandle: '@smithTrump.instagram'
}, {
  id: 6,
  avatar: '/assets/images/face2.jpg',
  name: 'Offical Team Trump',
  biography: 'Welcome to the official Team Trump Account',
  date: 'Jan 1, 2018',
  isChecked: false,
  checkValue: 0,
  checkDate: 'Jan 1, 2018',
  isSelected: false,
  twitterHandle: '@officlaTrump.twitter',
  facebookHandle: '@officialTrump.facebook',
  instagramHandle: '@officialTrump.instagram'
}, {
  id: 7,
  avatar: '/assets/images/face3.jpg',
  name: 'Trump Inauguration',
  biography: 'The Official Account of the 58th Presidential Inaugural Committee',
  date: 'Jan 1, 2018',
  isChecked: false,
  checkValue: 0,
  checkDate: 'Jan 1, 2018',
  isSelected: false,
  twitterHandle: '@trumpInauguration.twitter',
  facebookHandle: '@trumpInauguration.facebook',
  instagramHandle: '@trumpInguration.instagram'
}, {
  id: 8,
  avatar: '/assets/images/face4.jpg',
  name: 'John Bezos',
  biography: 'Make cinema great again',
  date: 'Jan 21, 2015',
  isChecked: false,
  checkValue: 0,
  checkDate: 'Jan 1, 2018',
  isSelected: false,
  twitterHandle: '@johnBezos.twitter',
  facebookHandle: '@johmBezos.facebook',
  instagramHandle: '@johmBezos.instagram'
}, {
  id: 9,
  avatar: '/assets/images/face5.jpg',
  name: 'Warren Modric',
  biography: 'Chief executive officer of Amazon',
  date: 'Jan 1, 2018',
  isChecked: false,
  checkValue: 0,
  checkDate: 'Jan 1, 2018',
  isSelected: false,
  twitterHandle: '@warrenModric.twitter',
  facebookHandle: '@warrenModric.facebook',
  instagramHandle: '@warrenModric.instagram'
}, {
  id: 10,
  avatar: '/assets/images/face1.jpg',
  name: 'Chris Ronaldo',
  biography: 'Portuguese footballer',
  date: 'Jan 1, 2018',
  isChecked: false,
  checkValue: 0,
  checkDate: 'Jan 1, 2018',
  isSelected: false,
  twitterHandle: '@chrisRonaldo.twitter',
  facebookHandle: '@chrisRonaldo.facebook',
  instagramHandle: '@ChrisRonaldo.instagram'
}, {
  id: 11,
  avatar: '/assets/images/face3.jpg',
  name: 'Lionel Messi',
  biography: 'Argentina footballer',
  date: 'Jan 1, 2018',
  isChecked: false,
  checkValue: 0,
  checkDate: 'Jan 1, 2018',
  isSelected: false,
  twitterHandle: '@lionelmessi.twitter',
  facebookHandle: '@lionelMessi.facebook',
  instagramHandle: '@lionelMessi.instagram'
}, {
  id: 12,
  avatar: '/assets/images/face5.jpg',
  name: 'Neymar',
  biography: 'Brazil footballer',
  date: 'Jan 1, 2018',
  isChecked: false,
  checkValue: 0,
  checkDate: 'Jan 1, 2018',
  isSelected: false,
  twitterHandle: '@neymar.twitter',
  facebookHandle: '@neymar.facebook',
  instagramHandle: '@neymar.instagram'
}];
